# This is a basic workflow to help you get started with Actions

name: write_README.md_file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # on:
  # schedule:
  #   - cron: '0 15 * * 0'  # Every Sunday, 15:00 UTC (== Monday 00:00 KST)

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.9'
          
      - name: echo data
        run: |
          ls -al
          pwd
          date
      
      - name: run py script
        run: python compute.py $(date '+%Y-%m-%d')

      - name: commit files 
        run: |
          git config --local user.name "algo bot"
          git add -A
          git commit -m "Update $(date '%m')/README.md"